/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class jason_DiffUtil */

#ifndef _Included_jason_DiffUtil
#define _Included_jason_DiffUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jason_DiffUtil
 * Method:    diffApk
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jason_DiffUtil_diffApk
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
